# -*- coding: utf-8 -*-
###############################################################################
# 業務設定情報
# 概要：業務共通のコード情報を記載
# Copyright:: Copyright (c) 2013 仲観派
# 作成日:2012/03/05 Nakanohito
# 更新日:
###############################################################################
ja:
  business:
    code_information:
      MATCH_COND_CLS:
        code_name: 一致条件区分
        code_values:
          E: と一致
          F: で始まる
          P: を含む
          B: で終わる

      COMP_COND_CLS: 
        code_name: 比較条件区分
        code_values:
          EQ: と一致
          NE: と不一致
          LT: より小さい
          GT: より大きい
          LE: 以下
          GE: 以上

      SORT_ORDER_CLS:
        code_name: ソート順序区分
        code_values:
          ASC: 昇順
          DESC: 降順

      COUNT_L:
        code_name: 件数
        code_values:
          10: 10
          50: 50
          100: 100
          300: 300
          500: 500

      DISP_NUMBER_S:
        code_name: 表示件数
        code_values:
          5: ５件
          8: ８件

      TIME_UNIT:
        code_name: 時間単位
        code_values:
          year: 年単位
          month: 月単位
          day: 日単位
          hour: 時単位
          minute: 分単位
          second: 秒単位

      MEMBER_SORT_FIELDS:
        code_name: 会員ソート項目
        code_values:
          open_id: OpenID
          member_id: 会員ID
          member_state_cls: 会員状態区分
          authority_cls: 権限区分
          nickname: ニックネーム
          email: メールアドレス
          join_date: 入会日時
          ineligibility_date: 資格停止日時
          last_login_date: 最終ログイン日時
          quote_cnt: 引用投稿回数
          quote_failure_cnt: 引用過失回数
          quote_correct_cnt: 引用訂正回数
          quote_correct_failure_cnt: 引用訂正過失回数
          comment_cnt: コメント投稿回数
          comment_failure_cnt: コメント過失回数
          comment_report_cnt: コメント通報回数
          were_reported_cnt: コメント被通報回数
          support_report_cnt: コメント通報対応

      NEWSPAPER_CLS:
        code_name: 新聞分類
        code_values:
          1: 朝刊
          2: 夕刊
          3: 号外

      SOURCE_NAME:
        code_name: 出所名
        code_values:
          1: newspaper
          2: magazine
          3: book
          4: tv
          5: radio
          6: music
          7: movie
          8: game
          9: news_site
          10: twitter
          11: blog
          12: sns
          13: bbs
          14: other_site
          15: other

      VALID_OP_PREFIX:
        code_name: 有効なOP接頭辞
        code_values:
          1: http://localhost:3001/open_id/user/
          2: https://id.mixi.jp/
#          2: yahoo.co.jp
          3: https://yahoo.co.jp
          4: openid.biglobe.ne.jp
          5: https://openid.biglobe.ne.jp/

      DELETE_STATE:
        code_name: 削除状態
        code_values:
          undeleted: 未削除
          deleted: 削除済み

      REPORT_SORT_FIELDS:
        code_name: 通報ソート項目
        code_values:
          quote_id: 引用ID
          quote_history_id: 引用履歴ID
          comment_id: コメントID
          comment_member_id: コメント会員ID
          report_date: 通報日時
          report_reason_id: 通報理由
          report_reason_detail: 通報理由詳細
          report_member_id: 通報会員ID
          report_member_nickname: 通報会員ニックネーム

en:
  business:
    code_information:
      MATCH_COND_CLS:
        code_name: Match conditions
        code_values:
          E: Match
          F: Begins with
          P: Including
          B: Ending in

      COMP_COND_CLS:
        code_name: Comparison conditions
        code_values:
          EQ: Equal to
          NE: Not Equal to
          LT: Less Than
          GT: Greater Than
          LE: Less than or Equal to
          GE: Greater than or Equal to

      SORT_ORDER_CLS:
        code_name: Classification sort order
        code_values:
          ASC: ASC
          DESC: DESC

      COUNT_L:
        code_name: Count
        code_values:
          ALL: All
          10: 10
          50: 50
          100: 100
          300: 300
          500: 500

      DISP_NUMBER_S:
        code_name: Display number 
        code_values:
          5: 5
          8: 8

      TIME_UNIT:
        code_name: Time unit
        code_values:
          year: years
          month: months
          day: days
          hour: hours
          minute: minutes
          second: seconds

      MEMBER_SORT_FIELDS:
        code_name: Member Sort Fields
        code_values:
          open_id: OpenID
          member_id: Member ID
          member_state_cls: Member State Class
          authority_cls: Authority Class
          nickname: Nickname
          email: Email
          join_date: Join date
          ineligibility_date: Ineligibility date
          last_login_date: Last login date
          quote_cnt: Quote count
          quote_failure_cnt: Quote failure count
          quote_correct_cnt: Quote correct count
          quote_correct_failure_cnt: Quote correct failure count
          comment_cnt: Comment count
          comment_failure_cnt: Comment failure count
          comment_report_cnt: Comment report count
          were_reported_cnt: were reported count
          support_report_cnt: support report count

      NEWSPAPER_CLS:
        code_name: Newspaper classified
        code_values:
          1: Morning newspaper
          2: Evening paper
          3: Extra edition

      SOURCE_NAME:
        code_name: Source name
        code_values:
          1: newspaper
          2: magazine
          3: book
          4: tv
          5: radio
          6: music
          7: movie
          8: game
          9: news_site
          10: twitter
          11: blog
          12: sns
          13: bbs
          14: other_site
          15: other

      VALID_OP_PREFIX:
        code_name: Valid OP
        code_values:
          1: https://id.mixi.jp/
          2: http://localhost:3001/open_id/user/

      DELETE_STATE:
        code_name: Delete State
        code_values:
          undeleted: Undeleted
          deleted: Deleted

      REPORT_SORT_FIELDS:
        code_name: Report Sort Fields
        code_values:
          quote_id: Quote ID
          quote_history_id: Quote history ID
          comment_id: Comment ID
          comment_member_id: Comment member ID
          report_date: Report datetime
          report_reason_id: Report reason
          report_reason_detail: Report reason_detail
          report_member_id: Report member ID
          report_member_nickname: Report member nickname

en-US:
  business:
    code_information:
      MATCH_COND_CLS:
        code_name: Match conditions
        code_values:
          E: Match
          F: Begins with
          P: Including
          B: Ending in

      COMP_COND_CLS:
        code_name: Comparison conditions
        code_values:
          EQ: Equal to
          NE: Not Equal to
          LT: Less Than
          GT: Greater Than
          LE: Less than or Equal to
          GE: Greater than or Equal to

      SORT_ORDER_CLS:
        code_name: Classification sort order
        code_values:
          ASC: ASC
          DESC: DESC

      COUNT_L:
        code_name: Count
        code_values:
          ALL: All
          10: 10
          50: 50
          100: 100
          300: 300
          500: 500

      DISP_NUMBER_S:
        code_name: Display number 
        code_values:
          5: 5
          8: 8

      TIME_UNIT:
        code_name: Time unit
        code_values:
          year: years
          month: months
          day: days
          hour: hours
          minute: minutes
          second: seconds

      MEMBER_SORT_FIELDS:
        code_name: Member Sort Fields
        code_values:
          open_id: OpenID
          member_id: Member ID
          member_state_cls: Member State Class
          authority_cls: Authority Class
          nickname: Nickname
          email: Email
          join_date: Join date
          ineligibility_date: Ineligibility date
          last_login_date: Last login date
          quote_cnt: Quote count
          quote_failure_cnt: Quote failure count
          quote_correct_cnt: Quote correct count
          quote_correct_failure_cnt: Quote correct failure count
          comment_cnt: Comment count
          comment_failure_cnt: Comment failure count
          comment_report_cnt: Comment report count
          were_reported_cnt: were reported count
          support_report_cnt: support report count

      NEWSPAPER_CLS:
        code_name: Newspaper classified
        code_values:
          1: Morning newspaper
          2: Evening paper
          3: Extra edition

      SOURCE_NAME:
        code_name: Source name
        code_values:
          1: newspaper
          2: magazine
          3: book
          4: tv
          5: radio
          6: music
          7: movie
          8: game
          9: news_site
          10: twitter
          11: blog
          12: sns
          13: bbs
          14: other_site
          15: other

      VALID_OP_PREFIX:
        code_name: Valid OP
        code_values:
          1: https://id.mixi.jp/
          2: http://localhost:3001/open_id/user/

      DELETE_STATE:
        code_name: Delete State
        code_values:
          undeleted: Undeleted
          deleted: Deleted

      REPORT_SORT_FIELDS:
        code_name: Report Sort Fields
        code_values:
          quote_id: Quote ID
          quote_history_id: Quote history ID
          comment_id: Comment ID
          comment_member_id: Comment member ID
          report_date: Report datetime
          report_reason_id: Report reason
          report_reason_detail: Report reason_detail
          report_member_id: Report member ID
          report_member_nickname: Report member nickname
