# -*- coding: utf-8 -*-
###############################################################################
# 業務設定情報
# 概要：業務共通のコード情報を記載
# Copyright:: Copyright (c) 2011 仲観派
# 作成日:2012/03/05 Nakanohito
# 更新日:
###############################################################################
ja:
  business:
    code_information:
      MATCH_COND_CLS:
        code_name: 一致条件区分
        code_values:
          E: と一致
          F: で始まる
          P: を含む
          B: で終わる

      COMP_COND_CLS: 
        code_name: 比較条件区分
        code_values:
          EQ: と一致
          NE: と不一致
          LT: より小さい
          GT: より大きい
          LE: 以下
          GE: 以上

      SORT_ORDER_CLS:
        code_name: ソート順序区分
        code_values:
          ASC: 昇順
          DESC: 降順

      COUNT_L:
        code_name: 件数
        code_values:
          10: 10
          50: 50
          100: 100
          300: 300
          500: 500

      MOBILE_CARRIER_CD:
        code_name: 携帯キャリアコード
        code_values:
          '00': ドコモ
          '01': AU
          '02': ソフトバンク
          '03': ディズニー
          '04': ウィルコム
          '05': イーモバイル

      SORT_FIELDS:
        code_name: ソート項目
        code_values:
          user_id: UserID
          member_state_id: 会員状態
          authority_cls: 権限
          nickname: ニックネーム
          country_name_cd: 居住国
          lang_name_cd: 言語
          timezone_id: タイムゾーン
          last_name: 名前（姓）
          first_name: 名前（名）
          yomigana_last: ヨミガナ（姓）
          yomigana_first: ヨミガナ（名）
          birth_date: 生年月日
          gender_cls: 性別
          postcode: 郵便番号
          email: メールアドレス
          mobile_carrier_id: 携帯キャリア
          mobile_phone_no: 携帯電話番号
          mobile_id_no: 個体識別番号
          mobile_email: 携帯メールアドレス
          join_date: 入会日時
          last_auth_date: 最終認証日時

      WITHDRAWAL_REASON_GENERAL:
        code_name: 退会理由
        code_values:
          PSC: 本人の都合
          OTC: 本人以外の都合
          OTH: その他

en:
  business:
    code_information:
      MATCH_COND_CLS:
        code_name: Match conditions
        code_values:
          E: Match
          F: Begins with
          P: Including
          B: Ending in

      COMP_COND_CLS:
        code_name: Comparison conditions
        code_values:
          EQ: Equal to
          NE: Not Equal to
          LT: Less Than
          GT: Greater Than
          LE: Less than or Equal to
          GE: Greater than or Equal to

      SORT_ORDER_CLS:
        code_name: Classification sort order
        code_values:
          ASC: ASC
          DESC: DESC

      COUNT_L:
        code_name: Count
        code_values:
          10: 10
          50: 50
          100: 100
          300: 300
          500: 500

      MOBILE_CARRIER_CD:
        code_name: Mobile Carrier Code
        code_values:
          '00': Docomo
          '01': au
          '02': Softbank
          '03': Disney
          '04': Willcom
          '05': EMobile

      SORT_FIELDS:
        code_name: Sort Fields
        code_values:
          user_id: UserID
          member_state_id: Member state
          authority_cls: Authority
          nickname: Nickname
          country_name_cd: Country
          lang_name_cd: Language
          timezone_id: Time zone
          last_name: Last name
          first_name: First name
          yomigana_last: Yomigana Last Name
          yomigana_first: Yomigana First Name
          birth_date: Birthday
          gender_cls: Gender
          postcode: Postcode
          email: Email address
          mobile_carrier_id: Mobile carrier
          mobile_phone_no: Mobile phone number
          mobile_id_no: Individual identification number
          mobile_email: Mobile Email address
          join_date: Join Date
          last_auth_date: Last authentication date

      WITHDRAWAL_REASON_GENERAL:
        code_name: Reason for withdrawal
        code_values:
          PSC: Person circumstances
          OTC: Circumstances of another person
          OTH: Other

en-US:
  business:
    code_information:
      MATCH_COND_CLS:
        code_name: Match conditions
        code_values:
          E: Match
          F: Begins with
          P: Including
          B: Ending in

      COMP_COND_CLS:
        code_name: Comparison conditions
        code_values:
          EQ: Equal to
          NE: Not Equal to
          LT: Less Than
          GT: Greater Than
          LE: Less than or Equal to
          GE: Greater than or Equal to

      SORT_ORDER_CLS:
        code_name: Classification sort order
        code_values:
          ASC: ASC
          DESC: DESC

      COUNT_L:
        code_name: Count
        code_values:
          10: 10
          50: 50
          100: 100
          300: 300
          500: 500

      MOBILE_CARRIER_CD:
        code_name: Mobile Carrier Code
        code_values:
          '00': Docomo
          '01': au
          '02': Softbank
          '03': Disney
          '04': Willcom
          '05': EMobile

      SORT_FIELDS:
        code_name: Sort Fields
        code_values:
          user_id: UserID
          member_state_id: Member state
          authority_cls: Authority
          nickname: Nickname
          country_name_cd: Country
          lang_name_cd: Language
          timezone_id: Time zone
          last_name: Last name
          first_name: First name
          yomigana_last: Yomigana Last Name
          yomigana_first: Yomigana First Name
          birth_date: Birthday
          gender_cls: Gender
          postcode: Postcode
          email: Email address
          mobile_carrier_id: Mobile carrier
          mobile_phone_no: Mobile phone number
          mobile_id_no: Individual identification number
          mobile_email: Mobile Email address
          join_date: Join Date
          last_auth_date: Last authentication date

      WITHDRAWAL_REASON_GENERAL:
        code_name: Reason for withdrawal
        code_values:
          PSC: Person circumstances
          OTC: Circumstances of another person
          OTH: Other
