# -*- coding: utf-8 -*-
###############################################################################
# Gemfile
# Copyright:: Copyright (c) 2011 仲観派
# 作成日:2011/01/16 Nakanohito  (mailto:)
# 更新日:
###############################################################################
source 'https://rubygems.org'

gem 'rails', '~> 3.2.6'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# Database
gem 'mysql2'
# domain search whois
gem 'whois'
# Rack Application
gem 'rack'
# Coverage Tool
gem 'simplecov'
# HTTP Client
gem 'httpclient'
# HTML Parser
gem 'nokogiri'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
